{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "app.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .envName }}
      remoteRef:
        {{- if .parameterPath }}
        # Use parameterPath for SSM Parameter Store
        key: {{ .parameterPath }}
        {{- else if .secretName }}
        # Fallback to secretName/secretKey for Secrets Manager
        key: {{ .secretName }}
        {{- if .secretKey }}
        property: {{ .secretKey }}
        {{- else }}
        property: {{ .envName }}
        {{- end }}
        {{- end }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
{{- end }}