{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nestjs-app.fullname" . }}-secrets
  labels:
    {{- include "nestjs-app.labels" . | nindent 4 }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "nestjs-app.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.secrets }}
    {{- if and .secretName .envName }}
    - secretKey: {{ .envName }}
      remoteRef:
        key: {{ .secretName }}
        {{- if .secretKey }}
        property: {{ .secretKey }}
        {{- else }}
        property: {{ .envName }}
        {{- end }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    {{- end }}
    {{- end }}
{{- end }}